version: '3.7'

services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  frontend:
    entrypoint: "echo 'service disabled'"
  database:
    restart: "no"
  resources:
    restart: "no"
  triplestore:
    ports:
      - "8890:8890"
    restart: "no"
  deltanotifier:
    restart: "no"
  uuid-generation:
    environment:
        RUN_CRON_JOBS: "true"
        CRON_FREQUENCY: "0 * * * *"
    ports:
      - "81:80"
    restart: "no"
  mandatendatabank-consumer:
    # environment:
    #   DCR_DISABLE_INITIAL_SYNC: "false" # uncomment to enable initial sync
    restart: "no"
  op-public-consumer:
    # environment:
    #   DCR_DISABLE_INITIAL_SYNC: "false" # uncomment to enable initial sync
    restart: "no"
  besluiten-consumer:
    # environment:
    #   DCR_DISABLE_INITIAL_SYNC: "false" # uncomment to enable initial sync
    restart: "no"
